#https://docs.docker.com/build/ci/github-actions/
name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - "app/src/**"  # Trigger action only when files in app/src change

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/src  # Set default working directory for all steps
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        working-directory: 
        uses: docker/build-push-action@v6
        with: ./app/src
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/mmg-web-app:latest
